# Generated by Django 4.1.7 on 2023-04-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=80, unique=True)),
                ('nombre_lista', models.CharField(max_length=80, unique=True)),
                ('carga', models.CharField(max_length=10, unique=True)),
                ('descarga', models.CharField(max_length=10, unique=True)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('puerto_api', models.IntegerField(default=8728)),
                ('direccion_ip', models.CharField(max_length=35, unique=True)),
                ('usuario', models.CharField(default='NETCOM', max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'routers',
                'ordering': ['hostname'],
                'unique_together': {('hostname', 'direccion_ip')},
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=80, unique=True)),
                ('nombre_cliente', models.CharField(max_length=80, unique=True)),
                ('direccion_ip', models.CharField(max_length=15, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_router.estado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='api_router.plan')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_router.router')),
            ],
            options={
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
